/**
 * Created by sergiodiazpinilla on 29/11/16.
 */
import angular from 'angular'
import 'angular-ui-router';
import 'angular-ui-grid';

angular.module('pensiones',["ui.router","ui.grid"])
    .config(($stateProvider,$urlRouterProvider) => {
        $urlRouterProvider.otherwise("/personas");

        $stateProvider
            .state("personas",{
                url:"/personas",
                templateUrl : "templates/personas-nav.html",
                resolve:{
                    personasService : function ($http) {
                        return $http.get("/personas");
                    }
                },
                controller : function (personasService) {
                    this.personas = personasService.data;
                },
                controllerAs:"personasCtrl"

            })
            .state("personas.id",{
                url:"/:idPersona",
                templateUrl:"templates/infomacion-persona.html",
                resolve:{
                    personasService : function ($q) {
                            return  $q((resolve,reject)=>{
                                let personData = {
                                    "name":"Ejemplo",
                                    "datosPension":[
                                        {
                                        fechaDesde: '1/01/74',
                                        fechaHasta: '31/12/74',
                                        IBC: '5790.00 ',
                                        year: 1974,
                                        diasEntre: 364,
                                        semanasAcumuladas: 154.57142857142858,
                                        factorIPC: 403.40548127,
                                        salarioActualizado: 2335717.7365533,
                                        IBLtlv: 850201256.1054013,
                                        numDias10Y: 0,
                                        IBL10Y: 0,
                                        numDiasuY: 0,
                                        IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/75',
                                            fechaHasta: '12/01/75',
                                            IBC: '5790.00 ',
                                            year: 1975,
                                            diasEntre: 11,
                                            semanasAcumuladas: 156.14285714285717,
                                            factorIPC: 322.72438501,
                                            salarioActualizado: 1868574.1892078998,
                                            IBLtlv: 20554316.0812869,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '13/01/75',
                                            fechaHasta: '31/01/75',
                                            IBC: '13260.00 ',
                                            year: 1975,
                                            diasEntre: 18,
                                            semanasAcumuladas: 158.71428571428575,
                                            factorIPC: 322.72438501,
                                            salarioActualizado: 4279325.3452326,
                                            IBLtlv: 77027856.2141868,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/02/75',
                                            fechaHasta: '31/07/75',
                                            IBC: '7470.00 ',
                                            year: 1975,
                                            diasEntre: 180,
                                            semanasAcumuladas: 184.42857142857147,
                                            factorIPC: 322.72438501,
                                            salarioActualizado: 2410751.1560247,
                                            IBLtlv: 433935208.084446,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/08/75',
                                            fechaHasta: '31/12/75',
                                            IBC: '9480.00 ',
                                            year: 1975,
                                            diasEntre: 152,
                                            semanasAcumuladas: 206.1428571428572,
                                            factorIPC: 322.72438501,
                                            salarioActualizado: 3059427.1698948,
                                            IBLtlv: 465032929.8240096,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/76',
                                            fechaHasta: '29/02/76',
                                            IBC: '9480.00 ',
                                            year: 1976,
                                            diasEntre: 59,
                                            semanasAcumuladas: 214.5714285714286,
                                            factorIPC: 274.61230855,
                                            salarioActualizado: 2603324.685054,
                                            IBLtlv: 153596156.418186,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/03/76',
                                            fechaHasta: '9/05/76',
                                            IBC: '11850.00 ',
                                            year: 1976,
                                            diasEntre: 69,
                                            semanasAcumuladas: 224.42857142857147,
                                            factorIPC: 274.61230855,
                                            salarioActualizado: 3254155.8563175,
                                            IBLtlv: 224536754.08590752,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '12/05/76',
                                            fechaHasta: '31/12/76',
                                            IBC: '9480.00 ',
                                            year: 1976,
                                            diasEntre: 233,
                                            semanasAcumuladas: 257.7142857142858,
                                            factorIPC: 274.61230855,
                                            salarioActualizado: 2603324.685054,
                                            IBLtlv: 606574651.617582,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/77',
                                            fechaHasta: '31/05/77',
                                            IBC: '9480.00 ',
                                            year: 1977,
                                            diasEntre: 150,
                                            semanasAcumuladas: 279.1428571428572,
                                            factorIPC: 218.64037305,
                                            salarioActualizado: 2072710.736514,
                                            IBLtlv: 310906610.4771,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/06/77',
                                            fechaHasta: '31/08/77',
                                            IBC: '11850.00 ',
                                            year: 1977,
                                            diasEntre: 91,
                                            semanasAcumuladas: 292.1428571428572,
                                            factorIPC: 218.64037305,
                                            salarioActualizado: 2590888.4206425,
                                            IBLtlv: 235770846.27846748,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/09/77',
                                            fechaHasta: '31/12/77',
                                            IBC: '17790.00 ',
                                            year: 1977,
                                            diasEntre: 121,
                                            semanasAcumuladas: 309.4285714285715,
                                            factorIPC: 218.64037305,
                                            salarioActualizado: 3889612.2365595,
                                            IBLtlv: 470643080.6236995,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/78',
                                            fechaHasta: '8/05/78',
                                            IBC: '17790.00 ',
                                            year: 1978,
                                            diasEntre: 127,
                                            semanasAcumuladas: 327.57142857142867,
                                            factorIPC: 171.54992001,
                                            salarioActualizado: 3051873.0769778998,
                                            IBLtlv: 387587880.77619326,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '9/05/78',
                                            fechaHasta: '1/06/78',
                                            IBC: '25530.00 ',
                                            year: 1978,
                                            diasEntre: 23,
                                            semanasAcumuladas: 330.85714285714295,
                                            factorIPC: 171.54992001,
                                            salarioActualizado: 4379669.4578553,
                                            IBLtlv: 100732397.5306719,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '2/06/78',
                                            fechaHasta: '31/12/78',
                                            IBC: '25530.00 ',
                                            year: 1978,
                                            diasEntre: 212,
                                            semanasAcumuladas: 361.1428571428572,
                                            factorIPC: 171.54992001,
                                            salarioActualizado: 4379669.4578553,
                                            IBLtlv: 928489925.0653236,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/79',
                                            fechaHasta: '30/09/79',
                                            IBC: '25530.00 ',
                                            year: 1979,
                                            diasEntre: 272,
                                            semanasAcumuladas: 400.00000000000006,
                                            factorIPC: 143.25671817,
                                            salarioActualizado: 3657344.0148801,
                                            IBLtlv: 994797572.0473871,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/10/79',
                                            fechaHasta: '31/12/79',
                                            IBC: '25530.00 ',
                                            year: 1979,
                                            diasEntre: 91,
                                            semanasAcumuladas: 413.00000000000006,
                                            factorIPC: 143.25671817,
                                            salarioActualizado: 3657344.0148801,
                                            IBLtlv: 332818305.3540891,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/80',
                                            fechaHasta: '31/03/80',
                                            IBC: '25530.00 ',
                                            year: 1980,
                                            diasEntre: 90,
                                            semanasAcumuladas: 425.8571428571429,
                                            factorIPC: 111.21552533,
                                            salarioActualizado: 2839332.3616749,
                                            IBLtlv: 255539912.55074102,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '15/10/81',
                                            fechaHasta: '31/12/81',
                                            IBC: '47370.00 ',
                                            year: 1981,
                                            diasEntre: 77,
                                            semanasAcumuladas: 436.8571428571429,
                                            factorIPC: 88.29431988,
                                            salarioActualizado: 4182501.9327156004,
                                            IBLtlv: 322052648.8191012,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/82',
                                            fechaHasta: '2/09/82',
                                            IBC: '47370.00 ',
                                            year: 1982,
                                            diasEntre: 244,
                                            semanasAcumuladas: 471.7142857142857,
                                            factorIPC: 69.87521358,
                                            salarioActualizado: 3309988.8672845997,
                                            IBLtlv: 807637283.6174424,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '6/09/82',
                                            fechaHasta: '30/10/82',
                                            IBC: '61950.00 ',
                                            year: 1982,
                                            diasEntre: 54,
                                            semanasAcumuladas: 479.42857142857144,
                                            factorIPC: 69.87521358,
                                            salarioActualizado: 4328769.481280999,
                                            IBLtlv: 233753551.98917395,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '17/11/82',
                                            fechaHasta: '31/12/82',
                                            IBC: '79290.00 ',
                                            year: 1982,
                                            diasEntre: 44,
                                            semanasAcumuladas: 485.7142857142857,
                                            factorIPC: 69.87521358,
                                            salarioActualizado: 5540405.684758199,
                                            IBLtlv: 243777850.12936077,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/83',
                                            fechaHasta: '30/09/83',
                                            IBC: '79290.00 ',
                                            year: 1983,
                                            diasEntre: 272,
                                            semanasAcumuladas: 524.5714285714286,
                                            factorIPC: 56.33734869,
                                            salarioActualizado: 4466988.3776301,
                                            IBLtlv: 1215020838.715387,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/10/83',
                                            fechaHasta: '31/12/83',
                                            IBC: '79290.00 ',
                                            year: 1983,
                                            diasEntre: 91,
                                            semanasAcumuladas: 537.5714285714286,
                                            factorIPC: 56.33734869,
                                            salarioActualizado: 4466988.3776301,
                                            IBLtlv: 406495942.36433905,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/84',
                                            fechaHasta: '31/03/84',
                                            IBC: '79290.00 ',
                                            year: 1984,
                                            diasEntre: 90,
                                            semanasAcumuladas: 550.4285714285714,
                                            factorIPC: 48.30019607,
                                            salarioActualizado: 3829722.5463902997,
                                            IBLtlv: 344675029.17512697,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/04/84',
                                            fechaHasta: '30/04/84',
                                            IBC: '136290.00 ',
                                            year: 1984,
                                            diasEntre: 29,
                                            semanasAcumuladas: 554.5714285714286,
                                            factorIPC: 48.30019607,
                                            salarioActualizado: 6582833.7223803,
                                            IBLtlv: 190902177.9490287,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/05/84',
                                            fechaHasta: '15/10/84',
                                            IBC: '150270.00 ',
                                            year: 1984,
                                            diasEntre: 167,
                                            semanasAcumuladas: 578.4285714285714,
                                            factorIPC: 48.30019607,
                                            salarioActualizado: 7258070.4634389,
                                            IBLtlv: 1212097767.3942964,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '5/02/85',
                                            fechaHasta: '11/02/85',
                                            IBC: '14610.00 ',
                                            year: 1985,
                                            diasEntre: 6,
                                            semanasAcumuladas: 579.2857142857143,
                                            factorIPC: 40.83547182,
                                            salarioActualizado: 596606.2432902,
                                            IBLtlv: 3579637.4597412003,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '12/02/85',
                                            fechaHasta: '31/05/85',
                                            IBC: '93900.00 ',
                                            year: 1985,
                                            diasEntre: 108,
                                            semanasAcumuladas: 594.7142857142858,
                                            factorIPC: 40.83547182,
                                            salarioActualizado: 3834450.803898,
                                            IBLtlv: 414120686.820984,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/06/85',
                                            fechaHasta: '31/12/85',
                                            IBC: '165180.00 ',
                                            year: 1985,
                                            diasEntre: 213,
                                            semanasAcumuladas: 625.1428571428572,
                                            factorIPC: 40.83547182,
                                            salarioActualizado: 6745203.235227601,
                                            IBLtlv: 1436728289.103479,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/86',
                                            fechaHasta: '31/12/86',
                                            IBC: '165180.00 ',
                                            year: 1986,
                                            diasEntre: 364,
                                            semanasAcumuladas: 677.1428571428572,
                                            factorIPC: 33.34869075,
                                            salarioActualizado: 5508536.738085001,
                                            IBLtlv: 2005107372.6629403,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/87',
                                            fechaHasta: '28/02/87',
                                            IBC: '165180.00 ',
                                            year: 1987,
                                            diasEntre: 58,
                                            semanasAcumuladas: 685.4285714285716,
                                            factorIPC: 27.57229495,
                                            salarioActualizado: 4554391.679841,
                                            IBLtlv: 264154717.43077797,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/03/87',
                                            fechaHasta: '31/12/87',
                                            IBC: '165180.00 ',
                                            year: 1987,
                                            diasEntre: 305,
                                            semanasAcumuladas: 729.0000000000001,
                                            factorIPC: 27.57229495,
                                            salarioActualizado: 4554391.679841,
                                            IBLtlv: 1389089462.3515048,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/88',
                                            fechaHasta: '29/02/88',
                                            IBC: '165180.00 ',
                                            year: 1988,
                                            diasEntre: 59,
                                            semanasAcumuladas: 737.4285714285716,
                                            factorIPC: 22.23213591,
                                            salarioActualizado: 3672304.2096138,
                                            IBLtlv: 216665948.3672142,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/03/88',
                                            fechaHasta: '16/06/88',
                                            IBC: '89070.00 ',
                                            year: 1988,
                                            diasEntre: 107,
                                            semanasAcumuladas: 752.7142857142859,
                                            factorIPC: 22.23213591,
                                            salarioActualizado: 1980216.3455037,
                                            IBLtlv: 211883148.96889588,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '17/06/88',
                                            fechaHasta: '30/06/88',
                                            IBC: '130110.00 ',
                                            year: 1988,
                                            diasEntre: 13,
                                            semanasAcumuladas: 754.5714285714288,
                                            factorIPC: 22.23213591,
                                            salarioActualizado: 2892623.2032501,
                                            IBLtlv: 37604101.6422513,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/07/88',
                                            fechaHasta: '31/08/88',
                                            IBC: '41040.00 ',
                                            year: 1988,
                                            diasEntre: 61,
                                            semanasAcumuladas: 763.2857142857144,
                                            factorIPC: 22.23213591,
                                            salarioActualizado: 912406.8577464,
                                            IBLtlv: 55656818.322530404,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '11/10/93',
                                            fechaHasta: '31/12/93',
                                            IBC: '977550.00 ',
                                            year: 1993,
                                            diasEntre: 81,
                                            semanasAcumuladas: 774.857142857143,
                                            factorIPC: 6.5504984,
                                            salarioActualizado: 6403439.71092,
                                            IBLtlv: 518678616.58452004,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/94',
                                            fechaHasta: '28/02/94',
                                            IBC: '977550.00 ',
                                            year: 1994,
                                            diasEntre: 58,
                                            semanasAcumuladas: 783.1428571428573,
                                            factorIPC: 5.34298401,
                                            salarioActualizado: 5223034.0189755,
                                            IBLtlv: 302935973.100579,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/03/94',
                                            fechaHasta: '31/03/94',
                                            IBC: '1000.000.00 ',
                                            year: 1994,
                                            diasEntre: 30,
                                            semanasAcumuladas: 787.4285714285717,
                                            factorIPC: 5.34298401,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/04/94',
                                            fechaHasta: '31/12/94',
                                            IBC: '1000.000.00 ',
                                            year: 1994,
                                            diasEntre: 274,
                                            semanasAcumuladas: 826.5714285714288,
                                            factorIPC: 5.34298401,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/95',
                                            fechaHasta: '30/11/95',
                                            IBC: '1000.000.00 ',
                                            year: 1995,
                                            diasEntre: 333,
                                            semanasAcumuladas: 874.1428571428573,
                                            factorIPC: 4.3584175,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/12/95',
                                            fechaHasta: '30/12/95',
                                            IBC: '1500.000.00 ',
                                            year: 1995,
                                            diasEntre: 29,
                                            semanasAcumuladas: 878.2857142857144,
                                            factorIPC: 4.3584175,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/96',
                                            fechaHasta: '30/11/96',
                                            IBC: '1000.000.00 ',
                                            year: 1996,
                                            diasEntre: 334,
                                            semanasAcumuladas: 926.0000000000001,
                                            factorIPC: 3.64843253,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/12/96',
                                            fechaHasta: '30/12/96',
                                            IBC: '1500.000.00 ',
                                            year: 1996,
                                            diasEntre: 29,
                                            semanasAcumuladas: 930.1428571428572,
                                            factorIPC: 3.64843253,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/97',
                                            fechaHasta: '30/11/97',
                                            IBC: '1000.000.00 ',
                                            year: 1997,
                                            diasEntre: 333,
                                            semanasAcumuladas: 977.7142857142858,
                                            factorIPC: 2.99961566,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/12/97',
                                            fechaHasta: '30/12/97',
                                            IBC: '1500.000.00 ',
                                            year: 1997,
                                            diasEntre: 29,
                                            semanasAcumuladas: 981.8571428571429,
                                            factorIPC: 2.99961566,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/98',
                                            fechaHasta: '30/08/98',
                                            IBC: '1000.000.00 ',
                                            year: 1998,
                                            diasEntre: 241,
                                            semanasAcumuladas: 1016.2857142857143,
                                            factorIPC: 2.5489596,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/09/98',
                                            fechaHasta: '30/09/98',
                                            IBC: '2000.000.00 ',
                                            year: 1998,
                                            diasEntre: 29,
                                            semanasAcumuladas: 1020.4285714285714,
                                            factorIPC: 2.5489596,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/10/98',
                                            fechaHasta: '30/11/98',
                                            IBC: '1000.000.00 ',
                                            year: 1998,
                                            diasEntre: 60,
                                            semanasAcumuladas: 1029,
                                            factorIPC: 2.5489596,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/12/98',
                                            fechaHasta: '30/12/98',
                                            IBC: '1500.000.00 ',
                                            year: 1998,
                                            diasEntre: 29,
                                            semanasAcumuladas: 1033.142857142857,
                                            factorIPC: 2.5489596,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/99',
                                            fechaHasta: '30/07/99',
                                            IBC: '1000.000.00 ',
                                            year: 1999,
                                            diasEntre: 210,
                                            semanasAcumuladas: 1063.142857142857,
                                            factorIPC: 2.18419846,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/08/99',
                                            fechaHasta: '6/08/99',
                                            IBC: '1000.000.00 ',
                                            year: 1999,
                                            diasEntre: 5,
                                            semanasAcumuladas: 1063.857142857143,
                                            factorIPC: 2.18419846,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/10/99',
                                            fechaHasta: '30/11/99',
                                            IBC: '1000.000.00 ',
                                            year: 1999,
                                            diasEntre: 60,
                                            semanasAcumuladas: 1072.4285714285716,
                                            factorIPC: 2.18419846,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/12/99',
                                            fechaHasta: '30/12/99',
                                            IBC: '1500.000.00 ',
                                            year: 1999,
                                            diasEntre: 29,
                                            semanasAcumuladas: 1076.5714285714287,
                                            factorIPC: 2.18419846,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/00',
                                            fechaHasta: '30/05/00',
                                            IBC: '1000.000.00 ',
                                            year: 2000,
                                            diasEntre: 150,
                                            semanasAcumuladas: 1098,
                                            factorIPC: 1.99963239,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/06/00',
                                            fechaHasta: '30/06/00',
                                            IBC: '5202.000.00 ',
                                            year: 2000,
                                            diasEntre: 29,
                                            semanasAcumuladas: 1102.142857142857,
                                            factorIPC: 1.99963239,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/07/00',
                                            fechaHasta: '30/12/00',
                                            IBC: '2800.000.00 ',
                                            year: 2000,
                                            diasEntre: 182,
                                            semanasAcumuladas: 1128.142857142857,
                                            factorIPC: 1.99963239,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/01',
                                            fechaHasta: '1/01/01',
                                            IBC: '93000.00 ',
                                            year: 2001,
                                            diasEntre: 0,
                                            semanasAcumuladas: 1128.142857142857,
                                            factorIPC: 1.83874243,
                                            salarioActualizado: 171003.04598999998,
                                            IBLtlv: 0,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/08/07',
                                            fechaHasta: '30/12/07',
                                            IBC: '1701.000.00 ',
                                            year: 2007,
                                            diasEntre: 151,
                                            semanasAcumuladas: 1149.7142857142858,
                                            factorIPC: 1.29718163,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/08',
                                            fechaHasta: '29/01/08',
                                            IBC: '1701.000.00 ',
                                            year: 2008,
                                            diasEntre: 28,
                                            semanasAcumuladas: 1153.7142857142858,
                                            factorIPC: 1.22734566,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/02/08',
                                            fechaHasta: '30/03/08',
                                            IBC: '1701.000.00 ',
                                            year: 2008,
                                            diasEntre: 58,
                                            semanasAcumuladas: 1162,
                                            factorIPC: 1.22734566,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/04/08',
                                            fechaHasta: '29/04/08',
                                            IBC: '1701.000.00 ',
                                            year: 2008,
                                            diasEntre: 28,
                                            semanasAcumuladas: 1166,
                                            factorIPC: 1.22734566,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/05/08',
                                            fechaHasta: '30/11/08',
                                            IBC: '1701.000.00 ',
                                            year: 2008,
                                            diasEntre: 213,
                                            semanasAcumuladas: 1196.4285714285713,
                                            factorIPC: 1.22734566,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/09',
                                            fechaHasta: '28/02/09',
                                            IBC: '1701.000.00 ',
                                            year: 2009,
                                            diasEntre: 58,
                                            semanasAcumuladas: 1204.7142857142856,
                                            factorIPC: 1.13991424,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/04/09',
                                            fechaHasta: '30/04/09',
                                            IBC: '1701.000.00 ',
                                            year: 2009,
                                            diasEntre: 29,
                                            semanasAcumuladas: 1208.8571428571427,
                                            factorIPC: 1.13991424,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/06/09',
                                            fechaHasta: '30/10/09',
                                            IBC: '1701.000.00 ',
                                            year: 2009,
                                            diasEntre: 151,
                                            semanasAcumuladas: 1230.4285714285713,
                                            factorIPC: 1.13991424,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/12/09',
                                            fechaHasta: '30/12/09',
                                            IBC: '1701.000.00 ',
                                            year: 2009,
                                            diasEntre: 29,
                                            semanasAcumuladas: 1234.5714285714284,
                                            factorIPC: 1.13991424,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/10',
                                            fechaHasta: '30/01/10',
                                            IBC: '1701.000.00 ',
                                            year: 2010,
                                            diasEntre: 29,
                                            semanasAcumuladas: 1238.7142857142856,
                                            factorIPC: 1.11756298,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/03/10',
                                            fechaHasta: '30/12/10',
                                            IBC: '1701.000.00 ',
                                            year: 2010,
                                            diasEntre: 304,
                                            semanasAcumuladas: 1282.1428571428569,
                                            factorIPC: 1.11756298,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/11',
                                            fechaHasta: '30/12/11',
                                            IBC: '1701.000.00 ',
                                            year: 2011,
                                            diasEntre: 363,
                                            semanasAcumuladas: 1333.9999999999998,
                                            factorIPC: 1.08322476,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/12',
                                            fechaHasta: '30/12/12',
                                            IBC: '1701.000.00 ',
                                            year: 2012,
                                            diasEntre: 364,
                                            semanasAcumuladas: 1385.9999999999998,
                                            factorIPC: 1.04427336,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 },
                                        {
                                            fechaDesde: '1/01/13',
                                            fechaHasta: '30/12/13',
                                            IBC: '1701.000.00 ',
                                            year: 2013,
                                            diasEntre: 363,
                                            semanasAcumuladas: 1437.8571428571427,
                                            factorIPC: 1.0194,
                                            salarioActualizado: NaN,
                                            IBLtlv: NaN,
                                            numDias10Y: 0,
                                            IBL10Y: 0,
                                            numDiasuY: 0,
                                            IBLuy: 0 } ]
                                };
                                resolve({data:personData});
                            });
                        }
                },
                controller: function(personasService) {
                    this.personData = personasService.data;
                },
                controllerAs : "personCtrl"
            });
    });

